### ISSUE TITLE
.NET reference assemblies error

### ISSUE THREAD

**Issue by tpartee-sv** [jimm98y/SharpMp4Parser#2]
When cloning this repo and attempting to build in the latest version of VS 2019 I get the following error:

```
The reference assemblies for ".NETFramework,Version=v6.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK
SharpMp4Parser.Tests
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	
```

I'm confused by this error requiring .Net Framework 6.0 when according to the README this library should be compatible with .Net 2.0
Is perhaps the source code .Net 2.0 compatible while the tests require a .Net 6.0 SDK, or is it something else?

Thanks for having a look.

**Comment by jimm98y** [comment]
Yes, the library is NETStandard2.0 and it should work also in VS2019. The tests are NET6. You can also use the compiled DLL from [nuget.org ](https://www.nuget.org/packages/SharpMp4Parser) that targets only netstandard2.0.
